# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "test",
      project_dir: "./"
    )
  end

  desc "Build a release APK/AAB without uploading"
  lane :build do
    gradle(
      task: "bundle", build_type: "Release",
      project_dir: "./"
    )
  end
  desc "Build a release APK/AAB without uploading"
    lane :deploy do
     # 1. Build the AAB instead of APK
     gradle(task: "bundle", build_type: "Release")

     # 2. Upload using GitHub Secret (json_key_data instead of json_key)
     upload_to_play_store(
       track: "internal", # can be internal, alpha, beta, production
       json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT"]
     )
   end
end

