name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java (Gradle requires Java)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"   # set your Flutter version

      # 4. Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Run Flutter tests
      - name: Run tests
        run: flutter test

      # 6. Build Android app (.apk or .aab)
      - name: Build release APK
        run: flutter build apk --release

      # Or if you want AAB for Play Store:
      # - name: Build release AAB
      #   run: flutter build appbundle --release

      # 7. Upload build artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk
